
local:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

amazon:
  service: PulitzerS3
  access_key_id: <%= ENV['AMZN_ASOC_KEY'] %>
  secret_access_key: <%= ENV['AMZN_ASOC_SECRET'] %>
  force_path_style: true
  region: us-west-1
  bucket: <%= ENV['FOG_DIRECTORY'] %>
